#!/bin/sh

usage() {
  echo
  echo "Usage: "
  echo "  ${0} <name>"
  echo
  echo "Names: "
  for src in test/fixtures/*.mkd; do
    src=${src##*/}
    echo "  ${src%.*}"
  done
}


: ${1:?"source name is required" "$(usage)"}

test -f "test/${1}_test.vim" && testfile="test/${1}_test.vim" || testfile="test/test.vim"

vim -gn ${testfile} +":source %" ${1}

